version: "3"
services:

    api:
        image: php:7.2-fpm-alpine3.7
        volumes:
            - ./api:/var/www/html/api
        working_dir: /var/www/html/api

    apidoc:
        build:
            context: .
            dockerfile: docker/Dockerfile-apidoc
        volumes:
            - ./docs/api/api.apib:/api/api.apib
            - ./docs/api/index.html:/api/index.html
        command: "-i api.apib --theme-full-width --no-theme-condense -o index.html"
    
    nginx:
        image: nginx:alpine
        volumes:
            - ./api:/var/www/html/api
            - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
        working_dir: /var/www/html/api
        restart: always
        ports:
            - "80:80"
        depends_on:
            - api
    
    composer:
        image: composer
        volumes:
            - ./api:/api
        working_dir: /api
        command: "install"
